[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pubmed-screen"
version = "1.0.0"
authors = [
    { name = "Rami Hamati", email = "rhamati95@gmail.com" }
]
dependencies = [
    "pandas >= 1.5.0, < 2",
    "requests >= 2.28.0, < 3",
    "beautifulsoup4 >= 4.11.0, < 5",
    "seaborn >= 0.12.0, < 1",
]

[project.scripts]
pmscreen = "pmscreen.main:main"
